//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class URLEntityProperties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal URLEntityProperties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.URLEntityProperties", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingActivitiesProperties.aspx.
        /// </summary>
        internal static string AccountingActivity {
            get {
                return ResourceManager.GetString("AccountingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingActivitiesLanguagesProperties.aspx.
        /// </summary>
        internal static string AccountingActivity_LG {
            get {
                return ResourceManager.GetString("AccountingActivity_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingScenariosProperties.aspx.
        /// </summary>
        internal static string AccountingScenario {
            get {
                return ResourceManager.GetString("AccountingScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingScenariosLanguagesProperties.aspx.
        /// </summary>
        internal static string AccountingScenario_LG {
            get {
                return ResourceManager.GetString("AccountingScenario_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingScopesProperties.aspx.
        /// </summary>
        internal static string AccountingScope {
            get {
                return ResourceManager.GetString("AccountingScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingScopesLanguagesProperties.aspx.
        /// </summary>
        internal static string AccountingScope_LG {
            get {
                return ResourceManager.GetString("AccountingScope_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingSectorsProperties.aspx.
        /// </summary>
        internal static string AccountingSector {
            get {
                return ResourceManager.GetString("AccountingSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/AccountingSectorsLanguagesProperties.aspx.
        /// </summary>
        internal static string AccountingSector_LG {
            get {
                return ResourceManager.GetString("AccountingSector_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/AddressesProperties.aspx.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ApplicabilitiesLanguageProperties.aspx.
        /// </summary>
        internal static string Applicability_LG {
            get {
                return ResourceManager.GetString("Applicability_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/BulkLoadMeasurementsProperties.aspx.
        /// </summary>
        internal static string BulkLoad {
            get {
                return ResourceManager.GetString("BulkLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationProperties.aspx.
        /// </summary>
        internal static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationCertificatesProperties.aspx.
        /// </summary>
        internal static string CalculationCertificate {
            get {
                return ResourceManager.GetString("CalculationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationEstimatesProperties.aspx.
        /// </summary>
        internal static string CalculationEstimate {
            get {
                return ResourceManager.GetString("CalculationEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ExtendedPropertyValuesProperties.aspx.
        /// </summary>
        internal static string CalculationExtendedProperty {
            get {
                return ResourceManager.GetString("CalculationExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationScenarioTypesProperties.aspx.
        /// </summary>
        internal static string CalculationScenarioType {
            get {
                return ResourceManager.GetString("CalculationScenarioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationScenarioTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string CalculationScenarioType_LG {
            get {
                return ResourceManager.GetString("CalculationScenarioType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationsLanguagesProperties.aspx.
        /// </summary>
        internal static string Calculation_LG {
            get {
                return ResourceManager.GetString("Calculation_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskExecutionCalibrationsProperties.aspx.
        /// </summary>
        internal static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceCatalogFilesProperties.aspx.
        /// </summary>
        internal static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ConfigurationExcelFilesProperties.aspx.
        /// </summary>
        internal static string ConfigurationExcelFile {
            get {
                return ResourceManager.GetString("ConfigurationExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ConstantsProperties.aspx.
        /// </summary>
        internal static string Constant {
            get {
                return ResourceManager.GetString("Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ConstantClassificationsProperties.aspx.
        /// </summary>
        internal static string ConstantClassification {
            get {
                return ResourceManager.GetString("ConstantClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ConstantClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string ConstantClassification_LG {
            get {
                return ResourceManager.GetString("ConstantClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ConstantsLanguagesProperties.aspx.
        /// </summary>
        internal static string Constant_LG {
            get {
                return ResourceManager.GetString("Constant_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/EmailsProperties.aspx.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/MessengersProperties.aspx.
        /// </summary>
        internal static string ContactMessenger {
            get {
                return ResourceManager.GetString("ContactMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ContactMessengersApplicationsProperties.aspx.
        /// </summary>
        internal static string ContactMessengerApplication {
            get {
                return ResourceManager.GetString("ContactMessengerApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ContactMessengersProvidersProperties.aspx.
        /// </summary>
        internal static string ContactMessengerProvider {
            get {
                return ResourceManager.GetString("ContactMessengerProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ContactTypesProperties.aspx.
        /// </summary>
        internal static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ContactTypesLanguageProperties.aspx.
        /// </summary>
        internal static string ContactType_LG {
            get {
                return ResourceManager.GetString("ContactType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/URLsProperties.aspx.
        /// </summary>
        internal static string ContactUrl {
            get {
                return ResourceManager.GetString("ContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/URLsLanguagesProperties.aspx.
        /// </summary>
        internal static string ContactUrl_LG {
            get {
                return ResourceManager.GetString("ContactUrl_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/CountriesProperties.aspx.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/CountriesLanguageProperties.aspx.
        /// </summary>
        internal static string Country_LG {
            get {
                return ResourceManager.GetString("Country_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskExecutionMeasurementsProperties.aspx.
        /// </summary>
        internal static string Datarecovery {
            get {
                return ResourceManager.GetString("Datarecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ImprovementActions/ExceptionProperties.aspx.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ExtendedPropertiesProperties.aspx.
        /// </summary>
        internal static string ExtendedProperty {
            get {
                return ResourceManager.GetString("ExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ExtendedPropertyClassificationsProperties.aspx.
        /// </summary>
        internal static string ExtendedPropertyClassification {
            get {
                return ResourceManager.GetString("ExtendedPropertyClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ExtendedPropertyClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string ExtendedPropertyClassification_LG {
            get {
                return ResourceManager.GetString("ExtendedPropertyClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ExtendedPropertiesLanguagesProperties.aspx.
        /// </summary>
        internal static string ExtendedProperty_LG {
            get {
                return ResourceManager.GetString("ExtendedProperty_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/GeographicDashboardFacilities.aspx.
        /// </summary>
        internal static string FacilitiesByProcess {
            get {
                return ResourceManager.GetString("FacilitiesByProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/FacilitiesProperties.aspx.
        /// </summary>
        internal static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/FacilityTypesProperties.aspx.
        /// </summary>
        internal static string FacilityType {
            get {
                return ResourceManager.GetString("FacilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/FacilityTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string FacilityType_LG {
            get {
                return ResourceManager.GetString("FacilityType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/FacilitiesLanguagesProperties.aspx.
        /// </summary>
        internal static string Facility_LG {
            get {
                return ResourceManager.GetString("Facility_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ImprovementActions/ExceptionProperties.aspx.
        /// </summary>
        internal static string FinishedTasks {
            get {
                return ResourceManager.GetString("FinishedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/FormulaProperties.aspx.
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ExtendedPropertyValuesProperties.aspx.
        /// </summary>
        internal static string FormulaExtendedProperty {
            get {
                return ResourceManager.GetString("FormulaExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/FormulasLanguagesProperties.aspx.
        /// </summary>
        internal static string Formula_LG {
            get {
                return ResourceManager.GetString("Formula_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/CollaborationTools/ForumsProperties.aspx.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/CollaborationTools/ForumsLanguagesProperties.aspx.
        /// </summary>
        internal static string Forum_LG {
            get {
                return ResourceManager.GetString("Forum_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/FunctionalAreasProperties.aspx.
        /// </summary>
        internal static string FunctionalArea {
            get {
                return ResourceManager.GetString("FunctionalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/FunctionalAreasLanguagesProperties.aspx.
        /// </summary>
        internal static string FunctionalArea_LG {
            get {
                return ResourceManager.GetString("FunctionalArea_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/FunctionalPositionsProperties.aspx.
        /// </summary>
        internal static string FunctionalPosition {
            get {
                return ResourceManager.GetString("FunctionalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/GeographicAreasProperties.aspx.
        /// </summary>
        internal static string GeographicArea {
            get {
                return ResourceManager.GetString("GeographicArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/GeographicAreasLanguageProperties.aspx.
        /// </summary>
        internal static string GeographicArea_LG {
            get {
                return ResourceManager.GetString("GeographicArea_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/GeographicFunctionalAreasProperties.aspx.
        /// </summary>
        internal static string GeographicFunctionalArea {
            get {
                return ResourceManager.GetString("GeographicFunctionalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/IndicatorsProperties.aspx.
        /// </summary>
        internal static string Indicator {
            get {
                return ResourceManager.GetString("Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/IndicatorClassificationsProperties.aspx.
        /// </summary>
        internal static string IndicatorClassification {
            get {
                return ResourceManager.GetString("IndicatorClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/IndicatorClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string IndicatorClassification_LG {
            get {
                return ResourceManager.GetString("IndicatorClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ExtendedPropertyValuesProperties.aspx.
        /// </summary>
        internal static string IndicatorExtendedProperty {
            get {
                return ResourceManager.GetString("IndicatorExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/IndicatorsLanguagesProperties.aspx.
        /// </summary>
        internal static string Indicator_LG {
            get {
                return ResourceManager.GetString("Indicator_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/JobTitlesProperties.aspx.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourcesProperties.aspx.
        /// </summary>
        internal static string KCResource {
            get {
                return ResourceManager.GetString("KCResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/LanguagesProperties.aspx.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MagnitudesProperties.aspx.
        /// </summary>
        internal static string Magnitud {
            get {
                return ResourceManager.GetString("Magnitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MagnitudesLanguagesProperties.aspx.
        /// </summary>
        internal static string Magnitud_LG {
            get {
                return ResourceManager.GetString("Magnitud_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskExecutionMeasurementsProperties.aspx.
        /// </summary>
        internal static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MeasurementDevicesProperties.aspx.
        /// </summary>
        internal static string MeasurementDevice {
            get {
                return ResourceManager.GetString("MeasurementDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MeasurementDeviceTypesProperties.aspx.
        /// </summary>
        internal static string MeasurementDeviceType {
            get {
                return ResourceManager.GetString("MeasurementDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MeasurementDeviceTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string MeasurementDeviceType_LG {
            get {
                return ResourceManager.GetString("MeasurementDeviceType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MeasurementUnitsProperties.aspx.
        /// </summary>
        internal static string MeasurementUnit {
            get {
                return ResourceManager.GetString("MeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MeasurementUnitsLanguagesProperties.aspx.
        /// </summary>
        internal static string MeasurementUnit_LG {
            get {
                return ResourceManager.GetString("MeasurementUnit_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MeasurementsLanguagesProperties.aspx.
        /// </summary>
        internal static string Measurement_LG {
            get {
                return ResourceManager.GetString("Measurement_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MethodologiesProperties.aspx.
        /// </summary>
        internal static string Methodology {
            get {
                return ResourceManager.GetString("Methodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/MethodologiesLanguagesProperties.aspx.
        /// </summary>
        internal static string Methodology_LG {
            get {
                return ResourceManager.GetString("Methodology_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ImprovementActions/ExceptionProperties.aspx.
        /// </summary>
        internal static string OpenedExceptions {
            get {
                return ResourceManager.GetString("OpenedExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskExecutionsProperties.aspx.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/OrganizationProperties.aspx.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/OrganizationalChartsProperties.aspx.
        /// </summary>
        internal static string OrganizationalChart {
            get {
                return ResourceManager.GetString("OrganizationalChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/OrganizationalChartsLanguageProperties.aspx.
        /// </summary>
        internal static string OrganizationalChart_LG {
            get {
                return ResourceManager.GetString("OrganizationalChart_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/OrganizationClassificationsProperties.aspx.
        /// </summary>
        internal static string OrganizationClassification {
            get {
                return ResourceManager.GetString("OrganizationClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/OrganizationClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string OrganizationClassification_LG {
            get {
                return ResourceManager.GetString("OrganizationClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ExtendedPropertyValuesProperties.aspx.
        /// </summary>
        internal static string OrganizationExtendedProperty {
            get {
                return ResourceManager.GetString("OrganizationExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/RelationshipsProperties.aspx.
        /// </summary>
        internal static string OrganizationRelationship {
            get {
                return ResourceManager.GetString("OrganizationRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/OrganizationsRelationShipsTypesProperties.aspx.
        /// </summary>
        internal static string OrganizationRelationshipType {
            get {
                return ResourceManager.GetString("OrganizationRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/OrganizationsRelationShipsTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string OrganizationRelationshipType_LG {
            get {
                return ResourceManager.GetString("OrganizationRelationshipType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ParametersProperties.aspx.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ParameterGroupsProperties.aspx.
        /// </summary>
        internal static string ParameterGroup {
            get {
                return ResourceManager.GetString("ParameterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ExtendedPropertyValuesProperties.aspx.
        /// </summary>
        internal static string ParameterGroupExtendedProperty {
            get {
                return ResourceManager.GetString("ParameterGroupExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ParameterGroupsLanguagesProperties.aspx.
        /// </summary>
        internal static string ParameterGroup_LG {
            get {
                return ResourceManager.GetString("ParameterGroup_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ParameterRangesProperties.aspx.
        /// </summary>
        internal static string ParameterRange {
            get {
                return ResourceManager.GetString("ParameterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/ParametersLanguagesProperties.aspx.
        /// </summary>
        internal static string Parameter_LG {
            get {
                return ResourceManager.GetString("Parameter_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ParticipationTypesProperties.aspx.
        /// </summary>
        internal static string ParticipationType {
            get {
                return ResourceManager.GetString("ParticipationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ParticipationTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string ParticipationType_LG {
            get {
                return ResourceManager.GetString("ParticipationType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/PeopleProperties.aspx.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/PositionsProperties.aspx.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/PositionsLanguagesProperties.aspx.
        /// </summary>
        internal static string Position_LG {
            get {
                return ResourceManager.GetString("Position_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/PostsProperties.aspx.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/DS/PresencesProperties.aspx.
        /// </summary>
        internal static string Presence {
            get {
                return ResourceManager.GetString("Presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessGroupProcessProperties.aspx.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessClassificationsProperties.aspx.
        /// </summary>
        internal static string ProcessClassification {
            get {
                return ResourceManager.GetString("ProcessClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string ProcessClassification_LG {
            get {
                return ResourceManager.GetString("ProcessClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ExtendedPropertyValuesProperties.aspx.
        /// </summary>
        internal static string ProcessExtendedProperty {
            get {
                return ResourceManager.GetString("ProcessExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessGroupNodeStandardProperties.aspx.
        /// </summary>
        internal static string ProcessGroupNode {
            get {
                return ResourceManager.GetString("ProcessGroupNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessGroupProcessProperties.aspx.
        /// </summary>
        internal static string ProcessGroupProcess {
            get {
                return ResourceManager.GetString("ProcessGroupProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessesLanguagesProperties.aspx.
        /// </summary>
        internal static string ProcessGroupProcess_LG {
            get {
                return ResourceManager.GetString("ProcessGroupProcess_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ParticipationProperties.aspx.
        /// </summary>
        internal static string ProcessParticipation {
            get {
                return ResourceManager.GetString("ProcessParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessResourcesProperties.aspx.
        /// </summary>
        internal static string ProcessResource {
            get {
                return ResourceManager.GetString("ProcessResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskCalibrationsProperties.aspx.
        /// </summary>
        internal static string ProcessTaskCalibration {
            get {
                return ResourceManager.GetString("ProcessTaskCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskExecutionCalibrationsProperties.aspx.
        /// </summary>
        internal static string ProcessTaskExecutionCalibration {
            get {
                return ResourceManager.GetString("ProcessTaskExecutionCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskExecutionMeasurementsProperties.aspx.
        /// </summary>
        internal static string ProcessTaskExecutionMeasurement {
            get {
                return ResourceManager.GetString("ProcessTaskExecutionMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskExecutionsProperties.aspx.
        /// </summary>
        internal static string ProcessTaskExecutionOperation {
            get {
                return ResourceManager.GetString("ProcessTaskExecutionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskMeasurementsProperties.aspx.
        /// </summary>
        internal static string ProcessTaskMeasurement {
            get {
                return ResourceManager.GetString("ProcessTaskMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessesLanguagesProperties.aspx.
        /// </summary>
        internal static string ProcessTaskMeasurement_LG {
            get {
                return ResourceManager.GetString("ProcessTaskMeasurement_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/ProcessTaskOperationsProperties.aspx.
        /// </summary>
        internal static string ProcessTaskOperation {
            get {
                return ResourceManager.GetString("ProcessTaskOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ImprovementActions/ProjectClassificationsProperties.aspx.
        /// </summary>
        internal static string ProjectClassification {
            get {
                return ResourceManager.GetString("ProjectClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ImprovementActions/ProjectClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string ProjectClassification_LG {
            get {
                return ResourceManager.GetString("ProjectClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/QualitiesProperties.aspx.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/QualitiesLanguagesProperties.aspx.
        /// </summary>
        internal static string Quality_LG {
            get {
                return ResourceManager.GetString("Quality_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceCatalogFilesProperties.aspx.
        /// </summary>
        internal static string ResourceCatalog {
            get {
                return ResourceManager.GetString("ResourceCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceClassificationsProperties.aspx.
        /// </summary>
        internal static string ResourceClassification {
            get {
                return ResourceManager.GetString("ResourceClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string ResourceClassification_LG {
            get {
                return ResourceManager.GetString("ResourceClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/ExtendedPropertyValuesProperties.aspx.
        /// </summary>
        internal static string ResourceExtendedProperty {
            get {
                return ResourceManager.GetString("ResourceExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceFileStatesProperties.aspx.
        /// </summary>
        internal static string ResourceHistoryState {
            get {
                return ResourceManager.GetString("ResourceHistoryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceFileStatesLanguagesProperties.aspx.
        /// </summary>
        internal static string ResourceHistoryState_LG {
            get {
                return ResourceManager.GetString("ResourceHistoryState_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceTypesProperties.aspx.
        /// </summary>
        internal static string ResourceType {
            get {
                return ResourceManager.GetString("ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string ResourceType_LG {
            get {
                return ResourceManager.GetString("ResourceType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceFilesProperties.aspx.
        /// </summary>
        internal static string ResourceVersion {
            get {
                return ResourceManager.GetString("ResourceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/DS/ResponsibilitiesProperties.aspx.
        /// </summary>
        internal static string Responsibility {
            get {
                return ResourceManager.GetString("Responsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleConfigurationDS {
            get {
                return ResourceManager.GetString("RightJobTitleConfigurationDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleConfigurationIA {
            get {
                return ResourceManager.GetString("RightJobTitleConfigurationIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleConfigurationKC {
            get {
                return ResourceManager.GetString("RightJobTitleConfigurationKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleConfigurationPA {
            get {
                return ResourceManager.GetString("RightJobTitleConfigurationPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleConfigurationPF {
            get {
                return ResourceManager.GetString("RightJobTitleConfigurationPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleConfigurationRM {
            get {
                return ResourceManager.GetString("RightJobTitleConfigurationRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleMapDS {
            get {
                return ResourceManager.GetString("RightJobTitleMapDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleMapIA {
            get {
                return ResourceManager.GetString("RightJobTitleMapIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleMapKC {
            get {
                return ResourceManager.GetString("RightJobTitleMapKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleMapPA {
            get {
                return ResourceManager.GetString("RightJobTitleMapPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleMapPF {
            get {
                return ResourceManager.GetString("RightJobTitleMapPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleMapRM {
            get {
                return ResourceManager.GetString("RightJobTitleMapRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleOrganization {
            get {
                return ResourceManager.GetString("RightJobTitleOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/JobTitlesProperties.aspx.
        /// </summary>
        internal static string RightJobTitleProcess {
            get {
                return ResourceManager.GetString("RightJobTitleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonConfigurationDS {
            get {
                return ResourceManager.GetString("RightPersonConfigurationDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonConfigurationIA {
            get {
                return ResourceManager.GetString("RightPersonConfigurationIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonConfigurationKC {
            get {
                return ResourceManager.GetString("RightPersonConfigurationKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonConfigurationPA {
            get {
                return ResourceManager.GetString("RightPersonConfigurationPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonConfigurationPF {
            get {
                return ResourceManager.GetString("RightPersonConfigurationPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonConfigurationRM {
            get {
                return ResourceManager.GetString("RightPersonConfigurationRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonMapDS {
            get {
                return ResourceManager.GetString("RightPersonMapDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonMapIA {
            get {
                return ResourceManager.GetString("RightPersonMapIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonMapKC {
            get {
                return ResourceManager.GetString("RightPersonMapKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonMapPA {
            get {
                return ResourceManager.GetString("RightPersonMapPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonMapPF {
            get {
                return ResourceManager.GetString("RightPersonMapPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonMapRM {
            get {
                return ResourceManager.GetString("RightPersonMapRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonOrganization {
            get {
                return ResourceManager.GetString("RightPersonOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Security/SecurityPersonProperties.aspx.
        /// </summary>
        internal static string RightPersonProcess {
            get {
                return ResourceManager.GetString("RightPersonProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/RiskManagement/RiskClassificationsProperties.aspx.
        /// </summary>
        internal static string RiskClassification {
            get {
                return ResourceManager.GetString("RiskClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/RiskManagement/RiskClassificationsLanguagesProperties.aspx.
        /// </summary>
        internal static string RiskClassification_LG {
            get {
                return ResourceManager.GetString("RiskClassification_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/ProcessesFramework/RoleTypesProperties.aspx.
        /// </summary>
        internal static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/RoleTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string RoleType_LG {
            get {
                return ResourceManager.GetString("RoleType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/SalutationTypesProperties.aspx.
        /// </summary>
        internal static string SalutationType {
            get {
                return ResourceManager.GetString("SalutationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/SalutationTypesLanguagesProperties.aspx.
        /// </summary>
        internal static string SalutationType_LG {
            get {
                return ResourceManager.GetString("SalutationType_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/SectorsProperties.aspx.
        /// </summary>
        internal static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/SectorsLanguagesProperties.aspx.
        /// </summary>
        internal static string Sector_LG {
            get {
                return ResourceManager.GetString("Sector_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/TelephonesProperties.aspx.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/TimeUnitsLanguagesProperties.aspx.
        /// </summary>
        internal static string TimeUnit_LG {
            get {
                return ResourceManager.GetString("TimeUnit_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationOfTransformationsProperties.aspx.
        /// </summary>
        internal static string Transformation {
            get {
                return ResourceManager.GetString("Transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationOfTransformationsProperties.aspx.
        /// </summary>
        internal static string TransformationByTransformation {
            get {
                return ResourceManager.GetString("TransformationByTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationOfTransformationsLanguagesProperties.aspx.
        /// </summary>
        internal static string TransformationByTransformation_LG {
            get {
                return ResourceManager.GetString("TransformationByTransformation_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/PerformanceAssessment/CalculationOfTransformationsLanguagesProperties.aspx.
        /// </summary>
        internal static string Transformation_LG {
            get {
                return ResourceManager.GetString("Transformation_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/DirectoryServices/UsersProperties.aspx.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/AdministrationTools/KnowledgeCollaboration/ResourceFilesProperties.aspx.
        /// </summary>
        internal static string VersionFile {
            get {
                return ResourceManager.GetString("VersionFile", resourceCulture);
            }
        }
    }
}
