
// Generated by Pnyx Generation tool at :04/05/2009 17:17:45
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;
using System.Data.SqlClient;

namespace Condesus.EMS.DataAccess.CT.Entities
{
    internal class ForumMessages
    {
        internal ForumMessages() { }

        #region Read Functions
        //Trae todos los resources 
        internal IEnumerable<DbDataRecord> ReadAll()
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_ReadAll");
            SqlDataReader _reader = (SqlDataReader)_db.ExecuteReader(_dbCommand);

            try
            {
                foreach (DbDataRecord _record in _reader)
                {
                    yield return _record;
                }
            }
            finally
            {                
                _reader.Close();
            }
        }
        //trae el resource pedido
        internal IEnumerable<DbDataRecord> ReadById(Int64 IdMessage)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_ReadById");
            _db.AddInParameter(_dbCommand, "IdMessage", DbType.Int64, IdMessage);
            SqlDataReader _reader = (SqlDataReader)_db.ExecuteReader(_dbCommand);

            try
            {
                foreach (DbDataRecord _record in _reader)
                {
                    yield return _record;
                }
            }
            finally
            {
                _reader.Close();
            }
        }
        internal IEnumerable<DbDataRecord> ReadByPerson(Int64 IdPerson)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_ReadByPerson");
            _db.AddInParameter(_dbCommand, "IdPerson", DbType.Int64, IdPerson);
            SqlDataReader _reader = (SqlDataReader)_db.ExecuteReader(_dbCommand);
            try
            {
                foreach (DbDataRecord _record in _reader)
                {
                    yield return _record;
                }
            }
            finally
            {
                _reader.Close();
            }
        }
        internal IEnumerable<DbDataRecord> ReadByTopic(Int64 IdTopic)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_ReadByTopic");
            _db.AddInParameter(_dbCommand, "IdTopic", DbType.Int64, IdTopic);
            SqlDataReader _reader = (SqlDataReader)_db.ExecuteReader(_dbCommand);
            try
            {
                foreach (DbDataRecord _record in _reader)
                {
                    yield return _record;
                }
            }
            finally
            {
                _reader.Close();
            }
        }
        #endregion
        #region FK's
        #endregion
        #region Write Functions
        internal Int64 Create(Int64 IdTopic,Int64 IdPerson,DateTime PostedDate,DateTime LastEditedDate,String Text,Boolean IsNormal)
        {
            Database _db = DatabaseFactory.CreateDatabase();
            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_Create");
            _db.AddOutParameter(_dbCommand, "IdMessage", DbType.Int64, 18);
            _db.AddInParameter(_dbCommand, "IdTopic", DbType.Int64, IdTopic);
            _db.AddInParameter(_dbCommand, "IdPerson", DbType.Int64, IdPerson);
            _db.AddInParameter(_dbCommand, "PostedDate", DbType.DateTime, PostedDate);
            _db.AddInParameter(_dbCommand, "LastEditedDate", DbType.DateTime, LastEditedDate);
            _db.AddInParameter(_dbCommand, "Text", DbType.String, Text);
            _db.AddInParameter(_dbCommand, "IsNormal", DbType.Boolean, IsNormal);
            _db.ExecuteNonQuery(_dbCommand);
            //Retorna el identificador
            return Convert.ToInt64(_db.GetParameterValue(_dbCommand, "IdMessage"));
        }

        internal void Delete(Int64 IdMessage)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_Delete");
            _db.AddInParameter(_dbCommand, "IdMessage", DbType.Int64, IdMessage);
            _db.ExecuteNonQuery(_dbCommand);
        }

        internal void Update(Int64 IdMessage,DateTime LastEditedDate,String Text)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_Update");
            _db.AddInParameter(_dbCommand, "IdMessage", DbType.Int64, IdMessage);
            _db.AddInParameter(_dbCommand, "LastEditedDate", DbType.DateTime, LastEditedDate);
            _db.AddInParameter(_dbCommand, "Text", DbType.String, Text);
            _db.ExecuteNonQuery(_dbCommand);
        }

        internal void ChangeType(Int64 IdMessage, Boolean IsNormal)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumMessages_ChangeType");
            _db.AddInParameter(_dbCommand, "IdMessage", DbType.Int64, IdMessage);
            _db.AddInParameter(_dbCommand, "IsNormal", DbType.Boolean, IsNormal);
            //Ejecuta el comando
            _db.ExecuteNonQuery(_dbCommand);
        }
        #endregion


    }
}

