
// Generated by Pnyx Generation tool at :04/05/2009 17:17:45
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;
using System.Data.SqlClient;

namespace Condesus.EMS.DataAccess.CT.Entities
{
    internal class ForumPolls
    {
        internal ForumPolls() { }

        #region Read Functions
        //Trae todos los resources 
        internal IEnumerable<DbDataRecord> ReadAll()
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumPolls_ReadAll");
            SqlDataReader _reader = (SqlDataReader)_db.ExecuteReader(_dbCommand);

            try
            {
                foreach (DbDataRecord _record in _reader)
                {
                    yield return _record;
                }
            }
            finally
            {                
                _reader.Close();
            }
        }
        //trae el resource pedido
        internal IEnumerable<DbDataRecord> ReadById(Int64 IdPoll)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumPolls_ReadById");
            _db.AddInParameter(_dbCommand, "IdPoll", DbType.Int64, IdPoll);
            SqlDataReader _reader = (SqlDataReader)_db.ExecuteReader(_dbCommand);

            try
            {
                foreach (DbDataRecord _record in _reader)
                {
                    yield return _record;
                }
            }
            finally
            {
                _reader.Close();
            }
        }

        internal IEnumerable<DbDataRecord> ReadByMessage(Int64 IdMessage)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumPolls_ReadByMessage");
            _db.AddInParameter(_dbCommand, "IdMessage", DbType.Int64, IdMessage);
            SqlDataReader _reader = (SqlDataReader)_db.ExecuteReader(_dbCommand);
            try
            {
                foreach (DbDataRecord _record in _reader)
                {
                    yield return _record;
                }
            }
            finally
            {
                _reader.Close();
            }
        }
        #endregion
        #region FK's
        #endregion
        #region Write Functions
        internal Int64 Create(Int64 IdPerson, Int64 IdMessage, DateTime PollDate, Int16 Value)
        {
            Database _db = DatabaseFactory.CreateDatabase();
            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumPolls_Create");
            _db.AddInParameter(_dbCommand, "IdPerson", DbType.Int64, IdPerson);
            _db.AddInParameter(_dbCommand, "IdMessage", DbType.Int64, IdMessage);
            _db.AddInParameter(_dbCommand, "PollDate", DbType.DateTime, PollDate);
            _db.AddInParameter(_dbCommand, "Value", DbType.Int16, Value);
            _db.AddInParameter(_dbCommand, "IdPoll", DbType.Int64, 18);
            _db.ExecuteNonQuery(_dbCommand);
            //Retorna el identificador
            return Convert.ToInt64(_db.GetParameterValue(_dbCommand, "IdPoll"));
        }

        internal void Delete(Int64 IdPoll)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumPolls_Delete");
            _db.AddInParameter(_dbCommand, "IdPoll", DbType.Int64, IdPoll);
            _db.ExecuteNonQuery(_dbCommand);
        }

        internal void Update(Int64 IdPoll, Int16 Value)
        {
            Database _db = DatabaseFactory.CreateDatabase();

            DbCommand _dbCommand = _db.GetStoredProcCommand("CT_ForumPolls_Update");
            _db.AddInParameter(_dbCommand, "IdPoll", DbType.Int64, IdPoll);
            _db.AddInParameter(_dbCommand, "Value", DbType.Int16, Value);
            _db.ExecuteNonQuery(_dbCommand);
        }
        #endregion


    }
}

